### ISSUE TITLE
Component error: wattbox - cannot import name 'VOLT' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)

### ISSUE THREAD

**Issue by scubieman** [eseglem/hass-wattbox#7]
Getting this error. Tried updating in HACS and nothing. Any help would be great.

**Comment by weirded** [comment]
This PR fixes the issue for me: 
https://github.com/eseglem/hass-wattbox/pull/8

**Comment by eseglem** [comment]
Thanks @weirded. I merged the PR and pushed a new release. HACS should be able to pick it up. Unfortunately I haven't been able to spend much time with HA in a while so this has been a bit neglected. So I greatly appreciate it.

Closing the issue for now, but can re-open it if there is still an issue.
